import type { Metadata } from "next";
import Image from "next/image";
import "@/styles/legacy/about.css";

const description =
  "GadZeke is a hand-curated collection of quotes from the books that shaped Rami Zeke's thinking — real notes from real reading.";

export const metadata: Metadata = {
  title: "About GadZeke",
  description,
  alternates: { canonical: "/about" },
  openGraph: { title: "About GadZeke", description, url: "/about" },
  twitter: { title: "About GadZeke", description },
};

export default function AboutPage() {
  return (
    <main>
      <h1>About GadZeke</h1>

      <div className="image-container">
        <Image
          src="/images/about-imge1.jpeg"
          className="about-image"
          alt="A stack of books that inspired GadZeke"
          width={300}
          height={400}
          loading="lazy"
        />
        <Image
          src="/images/about-image2.jpeg"
          className="about-image"
          alt="An open book being read"
          width={300}
          height={400}
          loading="lazy"
        />
        <Image
          src="/images/about-image3.webp"
          className="about-image-phone-version"
          alt="A stack of books that inspired GadZeke"
          width={300}
          height={260}
          loading="lazy"
        />
      </div>

      <div className="about-content">
        <p>
          GadZeke is a home for the words that stuck. Every quote here was pulled from a book{" "}
          <span className="highlight">actually read</span> — underlined because it changed how
          something looked, not generated by AI or scraped from a list. Just the lines worth
          remembering, gathered one book at a time.
        </p>

        <p>
          Have a quote from your own reading that deserves a place here? Send it our way at{" "}
          <span className="highlight">ramizeke516@gmail.com</span> — we&apos;d love to see what&apos;s
          stuck with you.
        </p>

        <h3>Foundation</h3>

        <div>
          <p>
            GadZeke was created by Rami Zeke, who believes the best idea in a book is often just a
            sentence or two — and that a sentence worth underlining is worth sharing with someone
            who might need to read it today. This site is a running collection of those sentences,
            for anyone who loves books enough to want the best parts within easy reach.
          </p>
        </div>
      </div>
    </main>
  );
}
